services:
  server-info:
    image: efaruk/server-info:latest
    container_name: server-info
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8888:80
    healthcheck:
      test: curl --fail http://localhost:80/healthz || exit 1
      interval: 2s
      timeout: 60s
      retries: 3
