services:
  server-info:
    image: efaruk/server-info:latest
    container_name: server-info
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8888:80
