FROM mcr.microsoft.com/dotnet/aspnet:8.0

#RUN apt-get update && apt-get install -y curl

WORKDIR /app

ENV ASPNETCORE_URLS=http://+:80

COPY \
    ./publish ./

ENTRYPOINT ["/app/ServerInfo"]

EXPOSE 80
